name: 🔧 Dependencies Management

on:
  push:
    branches: [ main, develop, hotfix/* ]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/01-dependencies.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
  schedule:
    # Rulează zilnic la 2:00 AM UTC pentru security updates
    - cron: '0 2 * * *'

jobs:
  dependency-check:
    name: Check Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Check for outdated packages
        run: |
          echo "Checking for outdated packages..."
          pnpm outdated || true
          
      - name: Check for security vulnerabilities
        run: |
          echo "Checking for security vulnerabilities..."
          pnpm audit --audit-level moderate || true
          
      - name: Validate lockfile
        run: |
          echo "Validating pnpm-lock.yaml..."
          pnpm install --frozen-lockfile --prefer-offline
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
            .next/cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
            
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: dependency-check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run security audit
        run: |
          echo "Running comprehensive security audit..."
          pnpm audit --audit-level moderate
          
      - name: Check for known vulnerabilities
        run: |
          echo "Checking for known vulnerabilities..."
          npx audit-ci --moderate
          
      - name: Generate security report
        if: always()
        run: |
          echo "Generating security report..."
          pnpm audit --json > security-audit.json || true
          
      - name: Upload security report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-audit-report
          path: security-audit.json
